services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-root}"
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  config-serverms:
    image:  dhruv4096/config-serverms:latest
    container_name: config-serverms
    ports:
      - 8080:8080 
    depends_on:
      - servicereg 
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  servicereg:
    image:  dhruv4096/servicereg:latest
    container_name: servicereg
    ports:
      - "8761:8761" 
    depends_on:
      - rabbitmq
      - zipkin
      - postgres
      - pgadmin 
    networks:
      - microservice-network
      - postgres
   
  companyms:
    image:  dhruv4096/companyms:latest
    container_name: company
    ports:
      - 8082:8082 
    depends_on:
      - servicereg 
      - config-serverms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker      

  jobms:
    image:  dhruv4096/jobms:latest
    container_name: job
    ports:
      - 8081:8081 
    depends_on:
      - servicereg 
      - config-serverms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker 
      # - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE==http://servicereg:8761/eureka/

  reviewms:
    image:  dhruv4096/reviewms:latest
    container_name: review
    ports:
      - 8083:8083
    depends_on:
      - servicereg 
      - config-serverms
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker 

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - 9411:9411
    networks:
      - postgres
      - microservice-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - postgres
      - microservice-network

  gatewayms:
    image:  dhruv4096/gatewayms:latest
    container_name: gatewayms
    ports:
      - 8084:8084
    depends_on:
      - servicereg 
    networks:
      - microservice-network
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker         

networks:
    microservice-network:
      driver: bridge
    postgres:
      driver: bridge

volumes:
  postgres:
  pgadmin:
